<?php

namespace WeDevs\WePOS;

/**
 * React Scripts and Styles Class
 * Handles loading React-based frontend assets
 */
class ReactAssets
{
    public function __construct()
    {

        if (is_admin()) {
            add_action('admin_enqueue_scripts', [ $this, 'register' ], 5);
        } else {
            add_action('wepos_enqueue_scripts', [ $this, 'register' ], 5);
        }
    }

    /**
     * Register our app scripts and styles
     *
     * @return void
     */
    public function register()
    {
        $this->register_scripts($this->get_scripts());
        $this->register_styles($this->get_styles());
        $this->enqueue_all_scripts();
        $this->register_localize();
    }

    /**
     * Register scripts
     *
     * @param  array $scripts
     *
     * @return void
     */
    private function register_scripts($scripts)
    {
        foreach ($scripts as $handle => $script) {
            $deps      = isset($script['deps']) ? $script['deps'] : false;
            $in_footer = isset($script['in_footer']) ? $script['in_footer'] : false;
            $version   = isset($script['version']) ? $script['version'] : WEPOS_VERSION;

            wp_register_script($handle, $script['src'], $deps, $version, $in_footer);
        }
    }

    /**
     * Register styles
     *
     * @param  array $styles
     *
     * @return void
     */
    public function register_styles($styles)
    {
        foreach ($styles as $handle => $style) {
            $deps = isset($style['deps']) ? $style['deps'] : false;

            wp_register_style($handle, $style['src'], $deps, WEPOS_VERSION);
        }
    }

    /**
     * Get all registered scripts
     *
     * @return array
     */
    public function get_scripts()
    {
        // Get the asset data generated by wp-scripts
        $asset_file = WEPOS_PATH . '/assets/js/wepos-react.asset.php';
        $asset_data = array();

        if (file_exists($asset_file)) {
            $asset_data = include $asset_file;
        }

        $dependencies = isset($asset_data['dependencies']) ? $asset_data['dependencies'] : array();
        $version = isset($asset_data['version']) ? $asset_data['version'] : WEPOS_VERSION;

        // Add WePos-specific dependencies
        $dependencies = array_merge($dependencies, array( 'wepos-blockui', 'wepos-accounting' ));

        $scripts = [
            // Core WooCommerce scripts needed for POS functionality
            'wepos-blockui' => [
                'src'       => \WC()->plugin_url() . '/assets/js/jquery-blockui/jquery.blockUI.min.js',
                'deps'      => array( 'jquery' ),
                'in_footer' => true
            ],
            'wepos-accounting' => array(
                'src'       => \WC()->plugin_url() . '/assets/js/accounting/accounting.min.js',
                'deps'      => array( 'jquery' )
            ),
            // Main React application
            'wepos-react' => [
                'src'       => WEPOS_ASSETS . '/js/wepos-react.js',
                'deps'      => $dependencies,
                'version'   => $version,
                'in_footer' => true
            ],
        ];

        return $scripts;
    }

    /**
     * Get registered styles
     *
     * @return array
     */
    public function get_styles()
    {
        $styles = [
            // Keep essential icon and font styles from original
            'wepos-flaticon' => [
                'src' =>  WEPOS_ASSETS . '/css/flaticon.css'
            ],
            'wepos-font' => [
                'src' =>  WEPOS_ASSETS . '/css/fonts.css'
            ],
            // React application styles (generated by wp-scripts with Tailwind)
            'wepos-react' => [
                'src' =>  WEPOS_ASSETS . '/js/wepos-react.css'
            ],
        ];

        return $styles;
    }

    public function enqueue_all_scripts()
    {
        if (! is_admin()) {
            // Enqueue minimal required styles
            wp_enqueue_style('wepos-flaticon');
            wp_enqueue_style('wepos-font');
            wp_enqueue_style('wepos-react');

            // Load core scripts
            wp_enqueue_script('wepos-blockui');
            wp_enqueue_script('wepos-accounting');

            do_action('wepos_load_react_frontend_scripts');

            // Load main React application
            wp_enqueue_script('wepos-react');
        }
    }

    /**
     * Set localize script data for React application
     *
     * @since 1.0.0
     *
     * @return void
     */
    public function register_localize()
    {
        $localize_data = apply_filters('wepos_react_localize_data', [
            'rest' => array(
                'root'    => esc_url_raw(get_rest_url()),
                'nonce'   => wp_create_nonce('wp_rest'),
                'wcversion' => 'wc/v3',
                'posversion' => 'wepos/v1',
            ),
            'ajaxurl'                      => admin_url('admin-ajax.php'),
            'nonce'                        => wp_create_nonce('wepos_nonce'),
            'mon_decimal_point'            => \wc_get_price_decimal_separator(),
            'currency_format_num_decimals' => \wc_get_price_decimals(),
            'currency_format_symbol'       => \get_woocommerce_currency_symbol(),
            'currency_format_decimal_sep'  => esc_attr(\wc_get_price_decimal_separator()),
            'currency_format_thousand_sep' => esc_attr(\wc_get_price_thousand_separator()),
            'currency_format'              => esc_attr(str_replace(array( '%1$s', '%2$s' ), array( '%s', '%v' ), \get_woocommerce_price_format())),
            'rounding_precision'           => \wc_get_rounding_precision(),
            'admin_url'                    => get_admin_url(),
            'assets_url'                   => WEPOS_ASSETS,
            'placeholder_image'            => \wc_placeholder_img_src(),
            'ajax_loader'                  => WEPOS_ASSETS . '/images/spinner-2x.gif',
            'logout_url'                   => wp_logout_url(site_url()),
            'categories'                   => wepos_get_product_category(),
            'countries'                    => \WC()->countries->get_countries(),
            'states'                       => \WC()->countries->get_states(),
            'current_user_id'              => get_current_user_id(),
            'home_url'                     => home_url(),
            'wp_date_format'               => get_option('date_format'),
            'wp_time_format'               => get_option('time_format'),
            // React-specific configurations
            'app_mode'                     => 'react',
            'debug'                        => defined('WP_DEBUG') && WP_DEBUG,
        ]);

        // Localize data for React app - attach to the main React script
        wp_localize_script('wepos-react', 'wepos', $localize_data);
    }
}
